spring:
  datasource:
    username: root
    password: cardlan@2017
    url: jdbc:mysql://172.0.13.242:3306/gulimall_ums?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf-8
    driver-class-name:  com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-member
  redis:
    database: 6             # Redis数据库索引（默认为0）
    host: 47.107.120.118         # Redis服务器地址
    port: 6379              # Redis服务器连接端口
    password: cardlan        # Redis服务器连接密码（默认为空）
    jedis:
      pool:
        ## 连接池最大连接数（使用负值表示没有限制）
        #spring.redis.pool.max-active=8
        max-active: 1000
        ## 连接池最大阻塞等待时间（使用负值表示没有限制）
        #spring.redis.pool.max-wait=-1
        max-wait: -1
        ## 连接池中的最大空闲连接
        #spring.redis.pool.max-idle=8
        max-idle: 2
        ## 连接池中的最小空闲连接
        #spring.redis.pool.min-idle=0
        min-idle: 0
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000

