spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    alicloud:
      access-key: LTAI4G5NS9WWwfSz6DwKL3fE
      secret-key: NcGhIFB2pLsHqCdxpvy5zs02767UYQ
      oss:
        endpoint: oss-cn-shenzhen.aliyuncs.com
        bucket: ismrxiao
  application:
    name: gulimall-third-party


server:
  port: 30000
